<template>
  <div class="login-page">
    <section class="login-visual"><img :src="portalHero" alt="蓝白数字孪生传统宫殿建筑"/><div class="login-visual__copy"><span>HERITAGE PARK RESEARCH PLATFORM</span><h1>以数据与知识<br/>连接遗产研究</h1><p>面向遗址公园保护、科学研究和管理决策的数字研究门户。</p><router-link to="/"><el-icon><ArrowLeft /></el-icon>返回门户首页</router-link></div></section>
    <main class="login-panel"><div class="login-card"><div class="login-brand"><span><el-icon><OfficeBuilding /></el-icon></span><div><strong>遗址公园研究平台</strong><small>HERITAGE PARK RESEARCH PLATFORM</small></div></div><div class="login-heading"><span class="eyebrow">WELCOME BACK</span><h2>登录研究平台</h2><p>使用您的平台账号继续访问研究与管理工具。</p></div><el-alert v-if="!AUTH_ENABLED" title="当前环境已关闭登录验证，可直接返回门户使用。" type="info" :closable="false"/><el-form ref="formRef" :model="form" :rules="rules" label-position="top" @submit.prevent="handleLogin"><el-form-item label="用户名" prop="username"><el-input v-model="form.username" placeholder="请输入用户名" prefix-icon="User" size="large" autocomplete="username"/></el-form-item><el-form-item label="密码" prop="password"><el-input v-model="form.password" type="password" placeholder="请输入密码" prefix-icon="Lock" size="large" autocomplete="current-password" show-password @keyup.enter="handleLogin"/></el-form-item><el-button type="primary" size="large" :loading="loading" :disabled="!AUTH_ENABLED" class="login-submit" @click="handleLogin">登录</el-button><el-button v-if="!AUTH_ENABLED" size="large" class="login-submit" @click="$router.push('/')">进入门户</el-button></el-form><p class="login-help">登录问题请联系平台管理员；请勿在公共设备保存账号信息。</p></div></main>
  </div>
</template>

<script setup>
import { reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { useAuthStore } from '@/stores/auth'
import { AUTH_ENABLED } from '@/config/app'
import portalHero from '@/assets/images/portal-hero.webp'
const route=useRoute();const router=useRouter();const auth=useAuthStore();const formRef=ref();const loading=ref(false);const form=reactive({username:'',password:''});const rules={username:[{required:true,message:'请输入用户名',trigger:'blur'}],password:[{required:true,message:'请输入密码',trigger:'blur'}]}
async function handleLogin(){if(!AUTH_ENABLED)return;const valid=await formRef.value?.validate().catch(()=>false);if(!valid)return;loading.value=true;try{await auth.login(form.username,form.password);ElMessage.success('登录成功');router.push(String(route.query.redirect||'/'))}catch(error){ElMessage.error(error.response?.data?.detail||'登录失败')}finally{loading.value=false}}
</script>

<style scoped lang="scss">
.login-page{min-height:100vh;display:grid;grid-template-columns:1.25fr .75fr;background:#fff}.login-visual{position:relative;overflow:hidden;background:#f4f8ff}.login-visual>img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center}.login-visual__copy{max-width:650px;position:absolute;left:8%;bottom:9%;z-index:1;color:var(--text-primary)}.login-visual__copy>span{color:var(--brand-600);font-size:11px;font-weight:700;letter-spacing:.16em}.login-visual__copy h1{margin:14px 0 16px;font-size:clamp(42px,5vw,68px);line-height:1.12;letter-spacing:-.045em}.login-visual__copy p{max-width:520px;color:#536078;font-size:15px;line-height:1.8}.login-visual__copy a{width:fit-content;margin-top:24px;display:flex;align-items:center;gap:6px;color:var(--brand-600);text-decoration:none;font-size:13px}.login-panel{display:grid;place-items:center;padding:42px}.login-card{width:min(100%,430px)}.login-brand{display:flex;align-items:center;gap:11px}.login-brand>span{width:42px;height:42px;display:grid;place-items:center;border-radius:12px;color:#fff;background:var(--brand-600);font-size:22px;box-shadow:0 9px 22px rgba(37,99,235,.22)}.login-brand>div{display:grid}.login-brand strong{font-size:16px}.login-brand small{margin-top:4px;color:var(--text-tertiary);font-size:7px}.login-heading{margin:54px 0 28px}.login-heading h2{margin:9px 0;font-size:30px}.login-heading p{color:var(--text-secondary);font-size:13px;line-height:1.7}.login-card .el-alert{margin-bottom:18px}.login-submit{width:100%;margin:8px 0 0}.login-submit+.login-submit{margin-left:0}.login-help{margin-top:20px;color:var(--text-tertiary);font-size:11px;line-height:1.7}@media(max-width:900px){.login-page{grid-template-columns:1fr}.login-visual{min-height:330px}.login-visual__copy{left:24px;right:24px;bottom:24px}.login-visual__copy h1{font-size:40px}.login-visual__copy p{display:none}.login-panel{padding:36px 24px}.login-heading{margin-top:34px}}@media(max-width:520px){.login-visual{min-height:240px}.login-visual__copy h1{font-size:31px}.login-visual__copy>span{display:none}}
</style>
